version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
#    entrypoint: /bin/sh
#    user: root
    container_name: influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
 #     - PERSISTENCE.ENABLE=true
 #     - PERSISTENCE.SIZE=10Gi
 #     - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME liquid'
#      - INFLUXDB_ADMIN_USER=admin
#      - INFLUXDB_ADMIN_PASSWORD=xxxx
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
     # Mount for influxdb data directory and configuration
      - ./influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.5.21
#    entrypoint: /bin/sh
#    user: root
    container_name: grafana
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      # Waits until influxdb container is up
      influxdb:
        condition: service_healthy
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana_data:/var/lib/grafana

  k6:
    image: grafana/k6:latest
#    entrypoint: /bin/sh
#    user: root
    container_name: k6
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      # Waits until influxdb container is up
      influxdb:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts